name = "MandelbrotFractal"
uuid = "25bcf871-a26f-43da-bfb3-c134c21e41c1"
authors = ["behinger (s-ccs 001) <benedikt.ehinger@vis.uni-stuttgart.de> and contributors"]
version = "0.0.1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
